### ISSUE TITLE
Converting multiple SVG Google Charts chokes on Safari browser

### ISSUE THREAD

**Issue by kinless** [Xportability/css-to-pdf#25]
Prime example on Safari 9.0: [http://www.cloudformatter.com/GoogleCharts](http://www.cloudformatter.com/GoogleCharts)

Converting one chart takes about 10 seconds, but eventually does it. When you start trying to convert multiple charts, then Safari shows the spinning beach ball and locks up. You have to close the window and start over. This happens on my own project as well, which is trying to convert about 6 charts to one PDF. I've let it go for at least 5 minutes before having to close it out.

No other browser does this. Is this a Safari limitation?

**Comment by kbrown01** [comment]
Can you profile where the time is?

We do not have Safari on Mac to test but can find one. 

Also, what is the exact platform … Safari 9.0 on ?

 

What would be important is to see if it takes forever to format at the server ,,, or it takes forever for the local JS to run to scrape what is sent to the server.

 

I suspect it is not at the server side as the Google JS should be generating the same (or very close) SVGs for all platforms.

 

Kevin Brown

(707) 869-8353 Direct

(925) 395-1772 Mobile

skype:kbrown01

 <mailto:kevin.brown@xportability.com> kevin.brown@xportability.com

**Comment by kinless** [comment]
So far, it's Safari 9.0 on both Mac OS X 10.9.5 and 10.10.5 (Haven't tested on 10.11.x yet).

Both Chrome and Firefox work fine under Mac OS X, so it's possible it's a client-side issue. My system console log does record a timeout hang with the com.apple.WebKit.WebContent framework, but I don't know if sending the log file will help solve the problem.

**Comment by kbrown01** [comment]
I don;t think so. Unfortunately I do not have Mac to test but it seems that issue is in the code that actually creates the data to send to the server .. the way @cloudformatter works is to scrape the DOM of the current HTML for your div and modify it slightly and send to the server. It isn't in the server, it's the scrape which is all client-side. Not sure what can be done except someone with Mac and expertise to profile the JS and see if there is something in there that is killing performance on Mac.

**Comment by kbrown01** [comment]
Can't debug without input of Mac
