### ISSUE TITLE
Absolute positioned divs stretching across multiple pages

### ISSUE THREAD

**Issue by Puffton** [Xportability/css-to-pdf#32]
Hi, I have a layout with absolute positioned divs stretching across multiple pages. Several browsers are having a hard time with page breaks, and tend to just clip content as the page breaks. Can this library handle it?

**Comment by kbrown01** [comment]
This is because you can;t do what you are asking. It makes no "composition" sense to position something absolutely and then have it carry over multiple pages like a flow. You have to rethink the design.  I would note this is the issue with the way bootstrap grids work as they are mapped to floats in the browser world. This is OK within a browser that is *not* a page composition engine, it is a "single" page composition engine,. Floats cannot carry over from page to page in this way.
