### ISSUE TITLE
Google bar chart with scaleType: 'log' enabled

### ISSUE THREAD

**Issue by ikoukuhn** [Xportability/css-to-pdf#38]
If I have google chart with scaleType: 'log' enabled, the pdf bars doesn't show correctly:
https://drive.google.com/open?id=0B4vXYJx2hoDpRngxTHdIYUFZWU0
As you can see the bars is overlaying the labels.
Here's what the scaleType:log do:
https://developers.google.com/chart/interactive/docs/customizing_axes#axis-scale

And here's my jsfiddle:
https://jsfiddle.net/Ljmhvrp4/4/

**Comment by kbrown01** [comment]
You really need to fix the fiddles you send. You mix http and https and you also have errors like this:

 



arrayToDataTable is not defined. 

xepOnline is not defined because you post an https reference and then call things with http.

**Comment by ikoukuhn** [comment]
I've cleaned the code, here's my updated jsfiddle:
https://jsfiddle.net/Ljmhvrp4/8/
But I still can't get the mixed http & https to works on jsfiddle...
It's working fine on my local development though.

**Comment by kbrown01** [comment]
I have found the reason for the issue. The only solution you would have is to implement some code to fix (dumb) structures created by the charting solution. Here is what happens:

When you create that SVG dynamically, the actual chart is what you see rendered in our PDF *except* the bars have a clip path applied to clip their extended length.

Now, that clip path is also inside the actual SVG. However, the google chart code is giving the following URL for the clip path:

<g clip-path="url(http://fiddle.jshell.net/_display/#_ABSTRACT_RENDERER_ID_0)">

You will note that the full URL path is given to an internal anchor when it could have (should have) been just:

<g clip-path="url(#_ABSTRACT_RENDERER_ID_0)">

I say *should have* because this makes this SVG totally unusable outside of this html page. You would note that if you just copy the SVG out and save it and then view it separately, it would be broken just as it renders in our software. Our software is not going to go find it at that URL and it fact in JSFiddle that would be impossible because not even the full path is accessible as it doesn;t even have the fiddle # or anything and it would not even exist as it is dynamically generated.

So the backend software receives that URL for the clip path and of course it cannot find it (it does not exist) and you get no clip and the bars long longer.

So you only solution is to implement something that strips those URLs to the *real* local anchor it should be.

**Comment by kbrown01** [comment]
Here is an updated fiddle to show the issue. **It is not generic, I would leave that to you**. This basically removes the baseURI from the specification of the clip-path. This shows that the **proper** specification of the URL should not include the full path and it still works. 

And the PDF is perfect because of this.

http://jsfiddle.net/Ljmhvrp4/12/

You could make this generic by getting the baseURL from the SVG and stripping that string for all the clip-paths.
