### ISSUE TITLE
Question about images in PDF

### ISSUE THREAD

**Issue by AndyXGWang** [Xportability/css-to-pdf#40]
Hi Guys.

Hope you are doing great.

Here I have a question about images in PDF. I can generate PDF with image file which images located under domain. but can't see images which images not below my domain. such as following: 
src = www.wangfz.com/xxxx.jpg , successful
src= www.xxx.com/xxxx.jpg  failed.

Could you kindly help on this?

Thanks & BR
Andy

**Comment by kbrown01** [comment]
I would need a sample specific link because I have external ones that work. Example: I used our demo page and pasted in the image to the left. You can see that the link is to https://...on github and the formatted PDF has the image.

![image](https://cloud.githubusercontent.com/assets/723363/18560636/57d111ae-7b31-11e6-8ac6-62781f90e7c3.png)

**Comment by kbrown01** [comment]
No answer, closing for now.
