### ISSUE TITLE
Ordered list style?

### ISSUE THREAD

**Issue by adaptifyDesigns** [Xportability/css-to-pdf#59]
By default, ordered lists seem to be styled like unordered lists (with bullets, instead of numbers).

BUT, the scraped html (printed in the console) looks like this:

```html
<ol style="height: 91px; list-style-type: decimal; margin-top: 12px; margin-bottom: 12px; padding-left: 40px; width: 680.375px;">
    <li style="display: list-item; height: 15px; margin-top: 0px; margin-bottom: 4px; padding-left: 0px;">This</li>
</ol>
```

As you can see, the `list-style-type` property is correctly applied to the `<ol>` element. So I'm wondering why the list is formatted like an `<ul>` in the resulting pdf.

Any ideas?

**Comment by kbrown01** [comment]
Seems like an issue I tried to work at long ago. I see that I left a note on this page:

 

http://www.cloudformatter.com/CSS2Pdf.Demos.Lists

 

And the formatting in that page does not work either for the numbered lists.

The issue is somewhere in the XSL that is converting the submitted scraped HTML (cleaned to XML).

That XSL is here: http://xep.cloudformatter.com/doc/XSL/xeponline-fo-translate-2.xsl

As defined by this: xsl_stylesheet_declaration: '<?xml-stylesheet type="text/xsl" href="http://xep.cloudformatter.com/doc/XSL/xeponline-fo-translate-2.xsl"?>',

 

Give me a little time to investigate where the bug in the XSL is.

 

Kevin Brown

**Comment by kbrown01** [comment]
Fixed. Bug in the XSL. Tested at http://www.cloudformatter.com/CSS2Pdf.Demos.Lists and works as shown in the page.

**Comment by adaptifyDesigns** [comment]
Thanks!
