### ISSUE TITLE
Flexbox support?

### ISSUE THREAD

**Issue by jewbetcha** [Xportability/css-to-pdf#61]
Any plans or workarounds to support flexbox styles?

**Comment by kbrown01** [comment]
I am afraid not. There is good reason, flexing box grids *when combined with pagination* are not possible to do. Technically speaking in order to compose properly, the grid would have to be broken apart and flowed into grids of fixed height -- the height of a page. There is no simple (or even difficult) solution to such things. HTML and browsers are fine because they do not comprehend pagination -- or even worse --- different pagination size and flow requirements based on page positions within a flow (first, last, middle and left/right pages).
