### ISSUE TITLE
How do i redirect of the pdf is downloaded. Please help

### ISSUE THREAD

**Issue by noman0911** [Xportability/css-to-pdf#67]

**Comment by kbrown01** [comment]
It is not clear what you mean. If you examine the Javascript, you would see some things like this:

__postBackSuccess: function(Response) {
	    jQuery(document).trigger( "xepOnlineStatus", ["Finished"]);
		var base64 = jQuery(Response).find("Result").text();

So at that moment the PDF is in the object base64 (in base64 encoding).
Modify the Javascript so that you take that and post it to wherever you like, however you want.
You could post to a service and store in a server, attach to an email, whatever you like. That is the PDF.

**Comment by noman0911** [comment]
i mean after the pdf get downloaded I want to redirect to another page or show some message. How to do that?????

**Comment by kbrown01** [comment]
Easy. Write it, Yourself. In the Javascript.

**Comment by noman0911** [comment]
I did but than pdf does not get downloaded. Only redirect to that address.
