### ISSUE TITLE
Is there a way to change the name of the downloaded document?

### ISSUE THREAD

**Issue by phiden** [Xportability/css-to-pdf#9]
Right now, docs come down with a generic "document.pdf." Is there an option exposed that would let me set 'document' to something more descriptive? 

Thanks!

**Comment by kstubs** [comment]
Yes, see option filename.  Go here for complete reference:  http://www.cloudformatter.com/CSS2Pdf.APIDoc.Usage

**Comment by kbrown01** [comment]
You can.

We will update on GITHUB to the latest Javascript.

 

Or … go to here:

http://www.cloudformatter.com/CSS2Pdf.APIDoc.Usage

 

See there is now an option to name the file for download: 

*	filename - [default 'document'] Optionally used to name the downloaded file, the server will add the appropriate extension based on the mimetype of the requested document

You can either link to that Javascript which is the latest or download from there.

Note there are many changes in that Javascript and the backend service including support for many different files types as well as images.

 

Kevin Brown

@cloudformatter

**Comment by kbrown01** [comment]
And just as an FYI, the pages on the whole website are done this way (actually the site is all XML driven so the buttons are generated dynamically using the same ID of the div to format. So that ID is used to name the download file. You of course set you own string like this:

 

<li><a href="#" onclick="return xepOnline.Formatter.Format('Usage', {render:'download',filename:'Usage'});">As PDF</a></li>

 

This would result in a file named “Usage.pdf”

 

Kevin Brown

@xportability

**Comment by phiden** [comment]
Thanks very much!

**Comment by kstubs** [comment]
yvw
